/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapyRouteImport } from './routes/therapy'
import { Route as RidingSkillsRouteImport } from './routes/riding-skills'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const TherapyRoute = TherapyRouteImport.update({
  id: '/therapy',
  path: '/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const RidingSkillsRoute = RidingSkillsRouteImport.update({
  id: '/riding-skills',
  path: '/riding-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/riding-skills': typeof RidingSkillsRoute
  '/therapy': typeof TherapyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/riding-skills': typeof RidingSkillsRoute
  '/therapy': typeof TherapyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/riding-skills': typeof RidingSkillsRoute
  '/therapy': typeof TherapyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/riding-skills' | '/therapy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/riding-skills' | '/therapy'
  id: '__root__' | '/' | '/login' | '/register' | '/riding-skills' | '/therapy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RidingSkillsRoute: typeof RidingSkillsRoute
  TherapyRoute: typeof TherapyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapy': {
      id: '/therapy'
      path: '/therapy'
      fullPath: '/therapy'
      preLoaderRoute: typeof TherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riding-skills': {
      id: '/riding-skills'
      path: '/riding-skills'
      fullPath: '/riding-skills'
      preLoaderRoute: typeof RidingSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RidingSkillsRoute: RidingSkillsRoute,
  TherapyRoute: TherapyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
