/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapyRouteImport } from './routes/therapy'
import { Route as RidingSkillsRouteImport } from './routes/riding-skills'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RidingSkillsIndexRouteImport } from './routes/riding-skills.index'
import { Route as RidingSkillsNewRouteImport } from './routes/riding-skills.new'
import { Route as RidingSkillsIdRouteImport } from './routes/riding-skills.$id'
import { Route as HorseIdRouteImport } from './routes/horse.$id'
import { Route as RidingSkillsIdIndexRouteImport } from './routes/riding-skills.$id.index'
import { Route as RidingSkillsIdEditRouteImport } from './routes/riding-skills.$id.edit'

const TherapyRoute = TherapyRouteImport.update({
  id: '/therapy',
  path: '/therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const RidingSkillsRoute = RidingSkillsRouteImport.update({
  id: '/riding-skills',
  path: '/riding-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidingSkillsIndexRoute = RidingSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RidingSkillsRoute,
} as any)
const RidingSkillsNewRoute = RidingSkillsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RidingSkillsRoute,
} as any)
const RidingSkillsIdRoute = RidingSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RidingSkillsRoute,
} as any)
const HorseIdRoute = HorseIdRouteImport.update({
  id: '/horse/$id',
  path: '/horse/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RidingSkillsIdIndexRoute = RidingSkillsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RidingSkillsIdRoute,
} as any)
const RidingSkillsIdEditRoute = RidingSkillsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RidingSkillsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/riding-skills': typeof RidingSkillsRouteWithChildren
  '/therapy': typeof TherapyRoute
  '/horse/$id': typeof HorseIdRoute
  '/riding-skills/$id': typeof RidingSkillsIdRouteWithChildren
  '/riding-skills/new': typeof RidingSkillsNewRoute
  '/riding-skills/': typeof RidingSkillsIndexRoute
  '/riding-skills/$id/edit': typeof RidingSkillsIdEditRoute
  '/riding-skills/$id/': typeof RidingSkillsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/therapy': typeof TherapyRoute
  '/horse/$id': typeof HorseIdRoute
  '/riding-skills/new': typeof RidingSkillsNewRoute
  '/riding-skills': typeof RidingSkillsIndexRoute
  '/riding-skills/$id/edit': typeof RidingSkillsIdEditRoute
  '/riding-skills/$id': typeof RidingSkillsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/riding-skills': typeof RidingSkillsRouteWithChildren
  '/therapy': typeof TherapyRoute
  '/horse/$id': typeof HorseIdRoute
  '/riding-skills/$id': typeof RidingSkillsIdRouteWithChildren
  '/riding-skills/new': typeof RidingSkillsNewRoute
  '/riding-skills/': typeof RidingSkillsIndexRoute
  '/riding-skills/$id/edit': typeof RidingSkillsIdEditRoute
  '/riding-skills/$id/': typeof RidingSkillsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/riding-skills'
    | '/therapy'
    | '/horse/$id'
    | '/riding-skills/$id'
    | '/riding-skills/new'
    | '/riding-skills/'
    | '/riding-skills/$id/edit'
    | '/riding-skills/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/therapy'
    | '/horse/$id'
    | '/riding-skills/new'
    | '/riding-skills'
    | '/riding-skills/$id/edit'
    | '/riding-skills/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/riding-skills'
    | '/therapy'
    | '/horse/$id'
    | '/riding-skills/$id'
    | '/riding-skills/new'
    | '/riding-skills/'
    | '/riding-skills/$id/edit'
    | '/riding-skills/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RidingSkillsRoute: typeof RidingSkillsRouteWithChildren
  TherapyRoute: typeof TherapyRoute
  HorseIdRoute: typeof HorseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapy': {
      id: '/therapy'
      path: '/therapy'
      fullPath: '/therapy'
      preLoaderRoute: typeof TherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riding-skills': {
      id: '/riding-skills'
      path: '/riding-skills'
      fullPath: '/riding-skills'
      preLoaderRoute: typeof RidingSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riding-skills/': {
      id: '/riding-skills/'
      path: '/'
      fullPath: '/riding-skills/'
      preLoaderRoute: typeof RidingSkillsIndexRouteImport
      parentRoute: typeof RidingSkillsRoute
    }
    '/riding-skills/new': {
      id: '/riding-skills/new'
      path: '/new'
      fullPath: '/riding-skills/new'
      preLoaderRoute: typeof RidingSkillsNewRouteImport
      parentRoute: typeof RidingSkillsRoute
    }
    '/riding-skills/$id': {
      id: '/riding-skills/$id'
      path: '/$id'
      fullPath: '/riding-skills/$id'
      preLoaderRoute: typeof RidingSkillsIdRouteImport
      parentRoute: typeof RidingSkillsRoute
    }
    '/horse/$id': {
      id: '/horse/$id'
      path: '/horse/$id'
      fullPath: '/horse/$id'
      preLoaderRoute: typeof HorseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riding-skills/$id/': {
      id: '/riding-skills/$id/'
      path: '/'
      fullPath: '/riding-skills/$id/'
      preLoaderRoute: typeof RidingSkillsIdIndexRouteImport
      parentRoute: typeof RidingSkillsIdRoute
    }
    '/riding-skills/$id/edit': {
      id: '/riding-skills/$id/edit'
      path: '/edit'
      fullPath: '/riding-skills/$id/edit'
      preLoaderRoute: typeof RidingSkillsIdEditRouteImport
      parentRoute: typeof RidingSkillsIdRoute
    }
  }
}

interface RidingSkillsIdRouteChildren {
  RidingSkillsIdEditRoute: typeof RidingSkillsIdEditRoute
  RidingSkillsIdIndexRoute: typeof RidingSkillsIdIndexRoute
}

const RidingSkillsIdRouteChildren: RidingSkillsIdRouteChildren = {
  RidingSkillsIdEditRoute: RidingSkillsIdEditRoute,
  RidingSkillsIdIndexRoute: RidingSkillsIdIndexRoute,
}

const RidingSkillsIdRouteWithChildren = RidingSkillsIdRoute._addFileChildren(
  RidingSkillsIdRouteChildren,
)

interface RidingSkillsRouteChildren {
  RidingSkillsIdRoute: typeof RidingSkillsIdRouteWithChildren
  RidingSkillsNewRoute: typeof RidingSkillsNewRoute
  RidingSkillsIndexRoute: typeof RidingSkillsIndexRoute
}

const RidingSkillsRouteChildren: RidingSkillsRouteChildren = {
  RidingSkillsIdRoute: RidingSkillsIdRouteWithChildren,
  RidingSkillsNewRoute: RidingSkillsNewRoute,
  RidingSkillsIndexRoute: RidingSkillsIndexRoute,
}

const RidingSkillsRouteWithChildren = RidingSkillsRoute._addFileChildren(
  RidingSkillsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RidingSkillsRoute: RidingSkillsRouteWithChildren,
  TherapyRoute: TherapyRoute,
  HorseIdRoute: HorseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
